# Generated by Django 3.1.4 on 2021-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
