# Generated by Django 3.1.4 on 2021-02-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210206_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
