# Generated by Django 3.1.4 on 2021-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210206_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(default='KZ', max_length=50, verbose_name='Язык'),
        ),
    ]
